[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "projeto-ai"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]
format = "pyink --pyink-indentation 2 ."

[dependencies]
jupyter = ">=1.1.1,<2"
python = ">=3.12.5,<4"
pyprojroot = ">=0.3.0,<0.4"
pandas = ">=2.2.2,<3"
hiplot = ">=0.1.33,<0.2"
matplotlib = ">=3.9.2,<4"
pillow = ">=10.4.0,<11"
scikit-learn = ">=1.5.2,<2"
seaborn = ">=0.13.2,<0.14"
python-duckdb = ">=1.1.2,<2"
joblib = ">=1.4.2,<2"
imbalanced-learn = ">=0.12.4,<0.13"
pyink = ">=24.8.0,<25"
cvxopt = ">=1.3.2,<2"
icecream = ">=2.1.3,<3"
ruff = ">=0.8.6,<0.9"

[pypi-dependencies]
ucimlrepo = ">=0.0.7, <0.0.8"
